using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SynaptechERP.API.Migrations
{
    /// <inheritdoc />
    public partial class SeedDepartmentDesignationsCatalog : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_EmployeeEmployments_WorkLocations_WorkLocationId",
                table: "EmployeeEmployments");

            migrationBuilder.Sql(@"
            DROP TABLE IF EXISTS ""ChatChannelMembers"";
            DROP TABLE IF EXISTS ""ChatMessages"";
            DROP TABLE IF EXISTS ""ChatChannels"";
            DROP TABLE IF EXISTS ""WorkLocations"";
            ");

            migrationBuilder.DropIndex(
                name: "IX_EmployeeEmployments_WorkLocationId",
                table: "EmployeeEmployments");

            migrationBuilder.DropColumn(
                name: "WorkLocationId",
                table: "EmployeeEmployments");

            migrationBuilder.Sql(@"
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Employees' AND column_name='DepartmentId') THEN
                    ALTER TABLE ""Employees"" ADD COLUMN ""DepartmentId"" integer NULL;
                END IF;
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Employees' AND column_name='DesignationId') THEN
                    ALTER TABLE ""Employees"" ADD COLUMN ""DesignationId"" integer NULL;
                END IF;
            END $$;
            ");

            migrationBuilder.Sql(@"
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='AttendanceRecords' AND column_name='BreakLogs') THEN
                    ALTER TABLE ""AttendanceRecords"" ADD COLUMN ""BreakLogs"" character varying(4000) NULL;
                END IF;
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='AttendanceRecords' AND column_name='TotalBreakMinutes') THEN
                    ALTER TABLE ""AttendanceRecords"" ADD COLUMN ""TotalBreakMinutes"" integer NOT NULL DEFAULT 0;
                END IF;
            END $$;
            ");

            migrationBuilder.Sql(@"
            CREATE TABLE IF NOT EXISTS ""Conversations"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                ""Name"" character varying(100),
                ""Type"" character varying(20) NOT NULL,
                ""CreatedByUserId"" text,
                ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT (NOW()),
                ""UpdatedAt"" timestamp with time zone NOT NULL DEFAULT (NOW()),
                ""LastMessageAt"" timestamp with time zone NOT NULL DEFAULT (NOW()),
                CONSTRAINT ""PK_Conversations"" PRIMARY KEY (""Id"")
            );

            CREATE TABLE IF NOT EXISTS ""DepartmentDesignations"" (
                ""DepartmentId"" integer NOT NULL,
                ""DesignationId"" integer NOT NULL,
                CONSTRAINT ""PK_DepartmentDesignations"" PRIMARY KEY (""DepartmentId"", ""DesignationId""),
                CONSTRAINT ""FK_DepartmentDesignations_Departments_DepartmentId"" FOREIGN KEY (""DepartmentId"") REFERENCES ""Departments"" (""Id"") ON DELETE CASCADE,
                CONSTRAINT ""FK_DepartmentDesignations_Designations_DesignationId"" FOREIGN KEY (""DesignationId"") REFERENCES ""Designations"" (""Id"") ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS ""LeaveRequests"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                ""EmployeeId"" integer NOT NULL,
                ""EmployeeName"" text NOT NULL,
                ""LeaveType"" text NOT NULL,
                ""StartDate"" text NOT NULL,
                ""EndDate"" text NOT NULL,
                ""TotalDays"" integer NOT NULL,
                ""Reason"" text NOT NULL,
                ""Status"" text NOT NULL,
                ""AppliedOn"" timestamp with time zone NOT NULL,
                ""ApprovedBy"" text,
                ""ActionDate"" timestamp with time zone,
                CONSTRAINT ""PK_LeaveRequests"" PRIMARY KEY (""Id"")
            );

            CREATE TABLE IF NOT EXISTS ""PayrollRecords"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                ""EmployeeId"" integer NOT NULL,
                ""EmployeeName"" text NOT NULL,
                ""Email"" text NOT NULL,
                ""Department"" text NOT NULL,
                ""Role"" text NOT NULL,
                ""BaseSalary"" numeric(18,2) NOT NULL,
                ""Allowances"" numeric(18,2) NOT NULL,
                ""Deductions"" numeric(18,2) NOT NULL,
                ""DaysInMonth"" integer NOT NULL,
                ""PresentDays"" integer NOT NULL,
                ""ApprovedLeaveDays"" integer NOT NULL,
                ""PayableDays"" integer NOT NULL,
                ""EarnedBaseSalary"" numeric(18,2) NOT NULL,
                ""EarnedAllowances"" numeric(18,2) NOT NULL,
                ""NetSalary"" numeric(18,2) NOT NULL,
                ""Month"" character varying(10) NOT NULL,
                ""Year"" integer NOT NULL,
                ""Status"" character varying(50) NOT NULL,
                ""CreatedAt"" timestamp with time zone NOT NULL,
                ""UpdatedAt"" timestamp with time zone,
                CONSTRAINT ""PK_PayrollRecords"" PRIMARY KEY (""Id"")
            );

            CREATE TABLE IF NOT EXISTS ""Projects"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                ""Name"" character varying(200) NOT NULL,
                ""Description"" text,
                ""Owner"" text,
                ""Status"" character varying(50) NOT NULL,
                ""Progress"" integer NOT NULL,
                ""Color"" character varying(50) NOT NULL,
                ""Priority"" character varying(20) NOT NULL,
                ""StartDate"" text,
                ""Deadline"" text,
                ""Members"" text,
                ""CreatedAt"" timestamp with time zone NOT NULL,
                ""UpdatedAt"" timestamp with time zone,
                CONSTRAINT ""PK_Projects"" PRIMARY KEY (""Id"")
            );

            CREATE TABLE IF NOT EXISTS ""Tasks"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                ""ProjectId"" integer,
                ""ProjectName"" text,
                ""Title"" character varying(300) NOT NULL,
                ""Description"" text,
                ""Done"" boolean NOT NULL,
                ""AssignedTo"" text,
                ""AssignedToEmployeeId"" integer,
                ""DueDate"" text,
                ""Priority"" character varying(20) NOT NULL,
                ""Status"" character varying(50) NOT NULL,
                ""Comments"" text,
                ""Subtasks"" text,
                ""Attachments"" text,
                ""Activity"" text,
                ""CreatedAt"" timestamp with time zone NOT NULL,
                ""UpdatedAt"" timestamp with time zone,
                CONSTRAINT ""PK_Tasks"" PRIMARY KEY (""Id"")
            );

            CREATE TABLE IF NOT EXISTS ""ConversationMembers"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                ""ConversationId"" integer NOT NULL,
                ""UserId"" text NOT NULL,
                ""JoinedAt"" timestamp with time zone NOT NULL DEFAULT (NOW()),
                ""LastReadAt"" timestamp with time zone,
                CONSTRAINT ""PK_ConversationMembers"" PRIMARY KEY (""Id""),
                CONSTRAINT ""FK_ConversationMembers_Conversations_ConversationId"" FOREIGN KEY (""ConversationId"") REFERENCES ""Conversations"" (""Id"") ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS ""Messages"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                ""ConversationId"" integer NOT NULL,
                ""SenderUserId"" text NOT NULL,
                ""SenderName"" character varying(150) NOT NULL,
                ""Content"" text NOT NULL,
                ""SentAt"" timestamp with time zone NOT NULL DEFAULT (NOW()),
                ""EditedAt"" timestamp with time zone,
                ""DeletedAt"" timestamp with time zone,
                ""IsDeleted"" boolean NOT NULL,
                ""IsDelivered"" boolean NOT NULL,
                ""IsRead"" boolean NOT NULL,
                ""ReadAt"" timestamp with time zone,
                CONSTRAINT ""PK_Messages"" PRIMARY KEY (""Id""),
                CONSTRAINT ""FK_Messages_Conversations_ConversationId"" FOREIGN KEY (""ConversationId"") REFERENCES ""Conversations"" (""Id"") ON DELETE CASCADE
            );
            ");

            migrationBuilder.CreateIndex(
                name: "IX_Employees_DepartmentId",
                table: "Employees",
                column: "DepartmentId");

            migrationBuilder.CreateIndex(
                name: "IX_Employees_DesignationId",
                table: "Employees",
                column: "DesignationId");

            migrationBuilder.CreateIndex(
                name: "IX_ConversationMembers_ConversationId_UserId",
                table: "ConversationMembers",
                columns: new[] { "ConversationId", "UserId" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_DepartmentDesignations_DesignationId",
                table: "DepartmentDesignations",
                column: "DesignationId");

            migrationBuilder.CreateIndex(
                name: "IX_Messages_ConversationId",
                table: "Messages",
                column: "ConversationId");

            migrationBuilder.AddForeignKey(
                name: "FK_Employees_Departments_DepartmentId",
                table: "Employees",
                column: "DepartmentId",
                principalTable: "Departments",
                principalColumn: "Id",
                onDelete: ReferentialAction.SetNull);

            migrationBuilder.AddForeignKey(
                name: "FK_Employees_Designations_DesignationId",
                table: "Employees",
                column: "DesignationId",
                principalTable: "Designations",
                principalColumn: "Id",
                onDelete: ReferentialAction.SetNull);

            migrationBuilder.Sql(@"
            -- Insert missing departments if not existing
            INSERT INTO ""Departments"" (""Name"", ""Code"", ""Description"", ""Lead"", ""Color"", ""CreatedAt"")
            SELECT 'Developer', 'DE', 'Software Engineering & IT', NULL, 'indigo', NOW()
            WHERE NOT EXISTS (SELECT 1 FROM ""Departments"" WHERE LOWER(""Name"") = 'developer' OR LOWER(""Name"") = 'development' OR LOWER(""Name"") = 'it');

            INSERT INTO ""Departments"" (""Name"", ""Code"", ""Description"", ""Lead"", ""Color"", ""CreatedAt"")
            SELECT 'HR', 'HR', 'Human Resources & People Ops', NULL, 'purple', NOW()
            WHERE NOT EXISTS (SELECT 1 FROM ""Departments"" WHERE LOWER(""Name"") = 'hr');

            INSERT INTO ""Departments"" (""Name"", ""Code"", ""Description"", ""Lead"", ""Color"", ""CreatedAt"")
            SELECT 'Finance', 'FI', 'Accounts & Finance Management', NULL, 'emerald', NOW()
            WHERE NOT EXISTS (SELECT 1 FROM ""Departments"" WHERE LOWER(""Name"") = 'finance' OR LOWER(""Name"") = 'accounts');

            INSERT INTO ""Departments"" (""Name"", ""Code"", ""Description"", ""Lead"", ""Color"", ""CreatedAt"")
            SELECT 'Sales', 'SA', 'Sales & Business Development', NULL, 'amber', NOW()
            WHERE NOT EXISTS (SELECT 1 FROM ""Departments"" WHERE LOWER(""Name"") = 'sales' OR LOWER(""Name"") = 'business development');

            INSERT INTO ""Departments"" (""Name"", ""Code"", ""Description"", ""Lead"", ""Color"", ""CreatedAt"")
            SELECT 'Marketing', 'MA', 'Marketing & Brand Outreach', NULL, 'sky', NOW()
            WHERE NOT EXISTS (SELECT 1 FROM ""Departments"" WHERE LOWER(""Name"") = 'marketing');

            INSERT INTO ""Departments"" (""Name"", ""Code"", ""Description"", ""Lead"", ""Color"", ""CreatedAt"")
            SELECT 'Operations', 'OP', 'Operations & Support', NULL, 'teal', NOW()
            WHERE NOT EXISTS (SELECT 1 FROM ""Departments"" WHERE LOWER(""Name"") = 'operations' OR LOWER(""Name"") = 'support');

            INSERT INTO ""Departments"" (""Name"", ""Code"", ""Description"", ""Lead"", ""Color"", ""CreatedAt"")
            SELECT 'Management', 'MG', 'Executive & Leadership', NULL, 'coral', NOW()
            WHERE NOT EXISTS (SELECT 1 FROM ""Departments"" WHERE LOWER(""Name"") = 'management' OR LOWER(""Name"") = 'leadership');
            ");

            migrationBuilder.Sql(@"
            DO $$
            DECLARE
                dept_id INT;
                desig_id INT;
                catalog RECORD;
            BEGIN
                CREATE TEMP TABLE tmp_catalog (
                    dept_name TEXT,
                    desig_name TEXT,
                    desig_code VARCHAR(20)
                ) ON COMMIT DROP;

                -- Development / IT
                INSERT INTO tmp_catalog VALUES
                ('Developer', 'Software Development Intern', 'DEV_SW_INT'),
                ('Developer', 'Junior Software Developer', 'DEV_JR_SW'),
                ('Developer', 'Software Developer', 'DEV_SW_DEV'),
                ('Developer', 'Senior Software Developer', 'DEV_SR_SW'),
                ('Developer', 'Full Stack Developer', 'DEV_FULL_STACK'),
                ('Developer', 'Backend Developer', 'DEV_BACKEND'),
                ('Developer', 'Frontend Developer', 'DEV_FRONTEND'),
                ('Developer', 'Mobile App Developer', 'DEV_MOBILE'),
                ('Developer', 'QA Engineer', 'DEV_QA_ENG'),
                ('Developer', 'Automation Test Engineer', 'DEV_AUTO_QA'),
                ('Developer', 'DevOps Engineer', 'DEV_DEVOPS'),
                ('Developer', 'Cloud Engineer', 'DEV_CLOUD'),
                ('Developer', 'Data Analyst', 'DEV_DATA_ANALYST'),
                ('Developer', 'Data Scientist', 'DEV_DATA_SCI'),
                ('Developer', 'AI/ML Engineer', 'DEV_AI_ML'),
                ('Developer', 'UI/UX Designer', 'DEV_UI_UX'),
                ('Developer', 'Technical Lead', 'DEV_TECH_LEAD'),
                ('Developer', 'Engineering Manager', 'DEV_ENG_MGR'),
                ('Developer', 'Project Manager', 'DEV_PROJ_MGR'),
                ('Developer', 'Product Manager', 'DEV_PROD_MGR');

                -- HR
                INSERT INTO tmp_catalog VALUES
                ('HR', 'HR Intern', 'HR_INTERN'),
                ('HR', 'HR Executive', 'HR_EXEC'),
                ('HR', 'HR Associate', 'HR_ASSOC'),
                ('HR', 'HR Specialist', 'HR_SPEC'),
                ('HR', 'Senior HR Executive', 'HR_SR_EXEC'),
                ('HR', 'HR Manager', 'HR_MGR'),
                ('HR', 'HR Business Partner', 'HR_BP'),
                ('HR', 'Talent Acquisition Executive', 'HR_TA_EXEC'),
                ('HR', 'Recruiter', 'HR_RECRUITER'),
                ('HR', 'Recruitment Manager', 'HR_RECRUIT_MGR');

                -- Finance
                INSERT INTO tmp_catalog VALUES
                ('Finance', 'Accounts Intern', 'FIN_ACCT_INT'),
                ('Finance', 'Accounts Executive', 'FIN_ACCT_EXEC'),
                ('Finance', 'Accountant', 'FIN_ACCOUNTANT'),
                ('Finance', 'Senior Accountant', 'FIN_SR_ACCT'),
                ('Finance', 'Finance Executive', 'FIN_EXEC'),
                ('Finance', 'Finance Analyst', 'FIN_ANALYST'),
                ('Finance', 'Financial Controller', 'FIN_CONTROLLER'),
                ('Finance', 'Finance Manager', 'FIN_MGR'),
                ('Finance', 'Chief Financial Officer (CFO)', 'FIN_CFO');

                -- Sales
                INSERT INTO tmp_catalog VALUES
                ('Sales', 'Sales Intern', 'SALES_INTERN'),
                ('Sales', 'Sales Executive', 'SALES_EXEC'),
                ('Sales', 'Sales Associate', 'SALES_ASSOC'),
                ('Sales', 'Business Development Executive', 'BUS_DEV_EXEC'),
                ('Sales', 'Business Development Associate', 'BUS_DEV_ASSOC'),
                ('Sales', 'Business Development Manager', 'BUS_DEV_MGR'),
                ('Sales', 'Sales Manager', 'SALES_MGR'),
                ('Sales', 'Account Manager', 'SALES_ACCT_MGR'),
                ('Sales', 'Sales Director', 'SALES_DIR');

                -- Marketing
                INSERT INTO tmp_catalog VALUES
                ('Marketing', 'Marketing Intern', 'MKTG_INTERN'),
                ('Marketing', 'Marketing Executive', 'MKTG_EXEC'),
                ('Marketing', 'Digital Marketing Executive', 'MKTG_DIGITAL'),
                ('Marketing', 'Social Media Executive', 'MKTG_SOCIAL'),
                ('Marketing', 'Content Writer', 'MKTG_WRITER'),
                ('Marketing', 'Content Strategist', 'MKTG_STRATEGIST'),
                ('Marketing', 'SEO Specialist', 'MKTG_SEO'),
                ('Marketing', 'Marketing Manager', 'MKTG_MGR'),
                ('Marketing', 'Brand Manager', 'MKTG_BRAND_MGR');

                -- Operations
                INSERT INTO tmp_catalog VALUES
                ('Operations', 'Operations Intern', 'OPS_INTERN'),
                ('Operations', 'Operations Executive', 'OPS_EXEC'),
                ('Operations', 'Operations Associate', 'OPS_ASSOC'),
                ('Operations', 'Operations Manager', 'OPS_MGR'),
                ('Operations', 'Customer Support Executive', 'OPS_CUST_SUPP'),
                ('Operations', 'Customer Success Executive', 'OPS_CUST_SUCC'),
                ('Operations', 'Customer Success Manager', 'OPS_SUCC_MGR'),
                ('Operations', 'Administrative Executive', 'OPS_ADMIN_EXEC'),
                ('Operations', 'Office Administrator', 'OPS_OFFICE_ADMIN');

                -- Management
                INSERT INTO tmp_catalog VALUES
                ('Management', 'Team Lead', 'MGMT_TEAM_LEAD'),
                ('Management', 'Department Head', 'MGMT_DEPT_HEAD'),
                ('Management', 'General Manager', 'MGMT_GM'),
                ('Management', 'Operations Manager', 'MGMT_OPS_MGR'),
                ('Management', 'Director', 'MGMT_DIRECTOR'),
                ('Management', 'Vice President', 'MGMT_VP'),
                ('Management', 'Chief Operating Officer (COO)', 'MGMT_COO'),
                ('Management', 'Chief Executive Officer (CEO)', 'MGMT_CEO');

                FOR catalog IN SELECT * FROM tmp_catalog LOOP
                    SELECT ""Id"" INTO dept_id FROM ""Departments"" 
                    WHERE LOWER(""Name"") = LOWER(catalog.dept_name) OR LOWER(""Name"") LIKE LOWER(catalog.dept_name) || '%' 
                    LIMIT 1;

                    IF dept_id IS NOT NULL THEN
                        SELECT ""Id"" INTO desig_id FROM ""Designations"" WHERE LOWER(""Name"") = LOWER(catalog.desig_name);
                        IF desig_id IS NULL THEN
                            INSERT INTO ""Designations"" (""Name"", ""Code"", ""Description"", ""Status"", ""CreatedAt"")
                            VALUES (catalog.desig_name, catalog.desig_code, catalog.desig_name || ' position', 'Active', NOW())
                            RETURNING ""Id"" INTO desig_id;
                        END IF;

                        IF desig_id IS NOT NULL THEN
                            IF NOT EXISTS (SELECT 1 FROM ""DepartmentDesignations"" WHERE ""DepartmentId"" = dept_id AND ""DesignationId"" = desig_id) THEN
                                INSERT INTO ""DepartmentDesignations"" (""DepartmentId"", ""DesignationId"")
                                VALUES (dept_id, desig_id);
                            END IF;
                        END IF;
                    END IF;
                END LOOP;
            END $$;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Employees_Departments_DepartmentId",
                table: "Employees");

            migrationBuilder.DropForeignKey(
                name: "FK_Employees_Designations_DesignationId",
                table: "Employees");

            migrationBuilder.DropTable(
                name: "ConversationMembers");

            migrationBuilder.DropTable(
                name: "DepartmentDesignations");

            migrationBuilder.DropTable(
                name: "LeaveRequests");

            migrationBuilder.DropTable(
                name: "Messages");

            migrationBuilder.DropTable(
                name: "PayrollRecords");

            migrationBuilder.DropTable(
                name: "Projects");

            migrationBuilder.DropTable(
                name: "Tasks");

            migrationBuilder.DropTable(
                name: "Conversations");

            migrationBuilder.DropIndex(
                name: "IX_Employees_DepartmentId",
                table: "Employees");

            migrationBuilder.DropIndex(
                name: "IX_Employees_DesignationId",
                table: "Employees");

            migrationBuilder.DropColumn(
                name: "DepartmentId",
                table: "Employees");

            migrationBuilder.DropColumn(
                name: "DesignationId",
                table: "Employees");

            migrationBuilder.DropColumn(
                name: "BreakLogs",
                table: "AttendanceRecords");

            migrationBuilder.DropColumn(
                name: "TotalBreakMinutes",
                table: "AttendanceRecords");

            migrationBuilder.AddColumn<int>(
                name: "WorkLocationId",
                table: "EmployeeEmployments",
                type: "integer",
                nullable: true);

            migrationBuilder.CreateTable(
                name: "ChatChannels",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    CreatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false, defaultValueSql: "NOW()"),
                    CreatedByUserId = table.Column<string>(type: "text", nullable: true),
                    LastMessageAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false, defaultValueSql: "NOW()"),
                    Name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                    Type = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ChatChannels", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "WorkLocations",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Address = table.Column<string>(type: "character varying(250)", maxLength: 250, nullable: true),
                    City = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                    Code = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: true),
                    Country = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                    CreatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false, defaultValueSql: "NOW()"),
                    Description = table.Column<string>(type: "character varying(250)", maxLength: 250, nullable: true),
                    Name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    PostalCode = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: true),
                    State = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                    Status = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_WorkLocations", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "ChatChannelMembers",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    ChannelId = table.Column<int>(type: "integer", nullable: false),
                    JoinedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false, defaultValueSql: "NOW()"),
                    UserId = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ChatChannelMembers", x => x.Id);
                    table.ForeignKey(
                        name: "FK_ChatChannelMembers_ChatChannels_ChannelId",
                        column: x => x.ChannelId,
                        principalTable: "ChatChannels",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "ChatMessages",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    ChannelId = table.Column<int>(type: "integer", nullable: false),
                    Content = table.Column<string>(type: "text", nullable: false),
                    SenderName = table.Column<string>(type: "character varying(150)", maxLength: 150, nullable: false),
                    SenderUserId = table.Column<string>(type: "text", nullable: false),
                    SentAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false, defaultValueSql: "NOW()")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ChatMessages", x => x.Id);
                    table.ForeignKey(
                        name: "FK_ChatMessages_ChatChannels_ChannelId",
                        column: x => x.ChannelId,
                        principalTable: "ChatChannels",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_EmployeeEmployments_WorkLocationId",
                table: "EmployeeEmployments",
                column: "WorkLocationId");

            migrationBuilder.CreateIndex(
                name: "IX_ChatChannelMembers_ChannelId_UserId",
                table: "ChatChannelMembers",
                columns: new[] { "ChannelId", "UserId" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_ChatMessages_ChannelId",
                table: "ChatMessages",
                column: "ChannelId");

            migrationBuilder.CreateIndex(
                name: "IX_WorkLocations_Code",
                table: "WorkLocations",
                column: "Code",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_WorkLocations_Name",
                table: "WorkLocations",
                column: "Name",
                unique: true);

            migrationBuilder.AddForeignKey(
                name: "FK_EmployeeEmployments_WorkLocations_WorkLocationId",
                table: "EmployeeEmployments",
                column: "WorkLocationId",
                principalTable: "WorkLocations",
                principalColumn: "Id",
                onDelete: ReferentialAction.SetNull);
        }
    }
}
